package com.toparchy.platform.security.model;

// CREATEROLE, CREATEUSER, CREATEGROUP, ADDUSERTOGROUP, REMOVEUSERFROMGROUP,
// GRANTROLETOUSER, REVOKEROLEFROMUSER, GRANTROLETOUSERS,
// REVOKEROLEFROMUSERS, GRANTROLETOGROUP, REVOKEROLEFROMGROUP,
// GRANTROLETOGROUPS, REVOKEROLEFROMGROUPS, GRANTGROUPROLETOUSER,
// REVOKEGROUPROLEFROMUSER, FINDREALM, FINDREALMS, FINDUSER, FINDUSERS,
// FINDGROUP, FINDGROUPS, FINDROLE, FINDROLES, DELETEUSER, DELETEGROUP,
// DELETEROLE, DELETEUSERS, DELETEGROUPS, DELETEROLES;
public enum ApplicationRole {

	ROLEMANAGER, ROLEMNORMALUSER, GROUPMANAGER, GROUPNORMALUSER, USERMANAGER, USERNORMALUSER, REALMMANAGER, REALMNORMALUSER, WORKFLOWORIGINATOR, WORKFLOWPARTICIPATOR;
	private ApplicationRole() {
	}

	private ApplicationRole(String _name) {
		this._name = _name;
	}

	private String _name;

	public String get_name() {
		return _name;
	}

	public void set_name(String _name) {
		this._name = _name;
	}
}
